title: Adventures in KQL
author: Evgeny Ternovsky
email: eternovsky+kqlblog@gmail.com
description: A weekly(ish) discussion of solving interesting problems with KQL
github_username:  eternovsky
paginate: 5
markdown: kramdown
remote_theme: aterenin/minima-reboot
