title: Adventures in KQL
author: Evgeny Ternovsky
#email: your-email@domain.com

description:
  Discussing KQL through practical examples

disclaimer: 
  The content presented on this site is provided  as-is, and represents the author's own views and opinions without any association with his employer.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - posts.md
  - resources.md

# footer_icons:
# - username: eternovsky/
#  url: https://github.com/eternovsky/
#  icon: icon.svg

paginate: 5

markdown: kramdown
